development:
  adapter: redis
  url: "redis://localhost:6379/5"

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/5" } %>
  channel_prefix: count-dokku_production
